# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
staging-settings:
    rpcs:
        - chain-name: monad-testnet
          url: https://testnet-rpc.monad.xyz
        - chain-name: ethereum-testnet-sepolia
          url: https://ethereum-sepolia-rpc.publicnode.com
        - chain-name: ethereum-mainnet
          url: https://ethereum-rpc.publicnode.com
# ==========================================================================
production-settings:
    rpcs:
        - chain-name: monad-testnet
          url: https://testnet-rpc.monad.xyz
        - chain-name: ethereum-testnet-sepolia
          url: https://ethereum-sepolia-rpc.publicnode.com
        - chain-name: ethereum-mainnet
          url: https://ethereum-rpc.publicnode.com
