// Regenerated by scripts/generate-abis.sh from the compiled contracts -- do not hand-edit.
import AgentMemoryAbi from "./AgentMemory.json" with { type: "json" };
import AgentRegistryAbi from "./AgentRegistry.json" with { type: "json" };
import AgentVaultAbi from "./AgentVault.json" with { type: "json" };
import BetRouterAbi from "./BetRouter.json" with { type: "json" };
import MarketManagerAbi from "./MarketManager.json" with { type: "json" };
import OddsLockAbi from "./OddsLock.json" with { type: "json" };
import SettlementReceiverAbi from "./SettlementReceiver.json" with { type: "json" };

export {
  AgentMemoryAbi,
  AgentRegistryAbi,
  AgentVaultAbi,
  BetRouterAbi,
  MarketManagerAbi,
  OddsLockAbi,
  SettlementReceiverAbi,
};
